accounts/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),

	path('signup/', views.SignUpView.as_view(), name='signup'),
	path('settings/', views.UserUpdateView.as_view(), name='settings'),
	path('edit/', views.ProfileUpdateView.as_view(), name='edit_profile'),

	path('password/reset/', auth_views.PasswordResetView.as_view(
		template_name='accounts/password_reset/password_reset.html',
		email_template_name='accounts/password_reset/password_reset_email.html',
		subject_template_name='accounts/password_reset/password_reset_subject.html',
		success_url=reverse_lazy('accounts:password_reset_done')
		),
		name='password_reset'
	),
	path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset/password_reset_done.html'), name='password_reset_done'),
	re_path(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
		auth_views.PasswordResetConfirmView.as_view(
			template_name='accounts/password_reset/password_reset_confirm.html',
			success_url=reverse_lazy('accounts:passsword_reset_complete')
		),
		name='password_reset_confirm'
	),
	path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/password_reset_complete.html'), name='passsword_reset_complete'),

	path('password/change/', 
		auth_views.PasswordChangeView.as_view(
			template_name='accounts/password_change/password_change.html',
			success_url=reverse_lazy('accounts:password_change_done')
		),
		name='password_change'
	),
	path('password/change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
	path('explore/', views.ExploreView.as_view(), name='explore'),
	path('results/', views.search_results, name='search_results'),
	path('category/<int:pk>/', views.CategoryPostsView.as_view(), name='category'),
	path('article/new/', views.BlogPostCreateView.as_view(), name='new_article'),
	path('article/<slug:slug>/', views.BlogPostDetailView.as_view(), name='article'),
	path('article/<slug:slug>/comment/<int:pk>/edit/', views.BlogCommentUpdateView.as_view(), name='edit_comment'),
	path('author/<int:pk>/', views.UserDetailView.as_view(), name='author_profile'),
	path('author/<int:pk>/follow/', views.follow_author, name='follow_author'),
	path('author/<int:pk>/unfollow/', views.unfollow_author, name='unfollow_author')
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from accounts import urls as accounts_urls
from blog import urls as blog_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(blog_urls)),
    path('auth/', include(accounts_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field import modelfields
from . import validators

def upload_location(instance, filename):
	return f'img/profile_pictures/author{instance.user.pk}-picture'

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=False)
	about = models.CharField(max_length=250, null=True, blank=True)
	profile_picture = models.ImageField(upload_to=upload_location, default='img/profile_pictures/default.png')
	phone_number = modelfields.PhoneNumberField(null=True, blank=True)
	facebook_page = models.URLField(max_length=150, null=True, blank=True, validators=[validators.validate_facebook_url])
	twitter_profile = models.URLField(max_length=150, null=True, blank=True, validators=[validators.validate_twitter_url])
	instagram_profile = models.URLField(max_length=150, null=True, blank=True, validators=[validators.validate_instagram_url])

	def __str__(self):
		return f"{self.user.username}'s profile"

	def get_full_name(self):
		return f'{self.user.first_name} {self.user.last_name}'

	def get_ordered_posts(self):
		return self.user.posts.all().order_by('-date_published')

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class SignUpForm(UserCreationForm):
	email = forms.CharField(
		max_length=80,
		required=True,
		widget=forms.EmailInput()
	)

	first_name = forms.CharField(
		max_length=60,
		required=True,
		widget=forms.TextInput()
	)

	last_name = forms.CharField(
		max_length=60,
		required=True,
		widget=forms.TextInput()
	)

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

class UpdateUserForm(forms.ModelForm):
	email = forms.EmailField()

	first_name = forms.CharField(
		max_length=60,
		required=True,
		widget=forms.TextInput()
	)

	last_name = forms.CharField(
		max_length=60,
		required=True,
		widget=forms.TextInput()
	)

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email']

class UpdateProfileForm(forms.ModelForm):
	about = forms.CharField(
		widget=forms.Textarea(
			attrs={'rows': 4, 'placeholder': 'About me'}
		),
		required=False,
		help_text = 'Max characters amount is 250.'
	)

	class Meta:
		model = Profile
		fields = ['profile_picture', 'about', 'phone_number', 'instagram_profile', 'facebook_page', 'twitter_profile']
		help_texts = {'profile_picture': 'Square images are recomended.'}

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import SignUpForm, UpdateProfileForm, UpdateUserForm
from .models import Profile
from blog.views import SearchFormMixin

class SignUpView(CreateView, SearchFormMixin):
	model = User
	form_class = SignUpForm
	template_name = 'accounts/signup.html'

	def form_valid(self, form):
		user = form.save()
		profile = Profile.objects.create(user=user)
		profile.save()
		login(self.request, user)
		return redirect('blog:home')

@method_decorator(login_required, name='dispatch')
class UserUpdateView(UpdateView, SearchFormMixin):
    model = User
    form_class = UpdateUserForm
    template_name = "accounts/settings.html"
    success_url = reverse_lazy('accounts:settings')

    def get_object(self):
    	return self.request.user

    def form_valid(self, form):
    	super().form_valid(form)
    	return redirect('blog:author_profile', pk=self.object.pk)

@method_decorator(login_required, name='dispatch')
class ProfileUpdateView(UpdateView, SearchFormMixin):
    model = Profile
    form_class = UpdateProfileForm
    template_name = "accounts/edit_profile.html"
    success_url = reverse_lazy('accounts:edit_profile')

    def get_object(self):
    	return self.request.user.profile

    def form_valid(self, form):
    	super().form_valid(form)
    	return redirect('blog:author_profile', pk=self.object.user.pk)

@method_decorator(login_required, name='dispatch')
class PasswordChangeDone(TemplateView, SearchFormMixin):
    template_name = "accounts/password_change/password_change_done.html"

accounts/templates/accounts/base.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
	<link rel="stylesheet" href="{% static "css/accounts.css" %}">
	<link href="https://fonts.googleapis.com/css2?family=Overlock:ital,wght@0,900;1,700&display=swap" rel="stylesheet">
{% endblock stylesheets %}

{% block body %}
	<div class="columns center-v px-6">
		{% block left %}
			<div class="form column is-half px-6">
				<figure class="column image is-2by1 mx-6 mb-5 py-6 px-6 is-hidden-desktop">
					<img src="{% static "img/logopng.png" %}" alt="myblog logo">
				</figure>
				<div class="form pl-6 pr-4">
					{% block content_left %}
						
					{% endblock content_left %}
				</div>
			</div>
			<div class="vl is-hidden-mobile"></div>
		{% endblock left %}
		<div class="column is-half px-6 is-hidden-mobile">
			<a href="{% url 'blog:home' %}">
				<div class="columns is-centered">	
					<figure class="column image is-half">
						<img src="{% static "img/logopng.png" %}" alt="myblog logo">
					</figure>
				</div>
			</a>
		</div>
		{% block right %}
			<div class="vl is-hidden-mobile"></div>
			<div class="form column is-half px-6">
				<figure class="column image is-2by1 mx-6 mb-5 py-6 px-6 is-hidden-desktop">
					<img src="{% static "img/logopng.png" %}" alt="myblog logo">
				</figure>
				<div class="form pl-6 pr-4">
					{% block content_right %}
						
					{% endblock content_right %}
				</div>
			</div>
		{% endblock right %}
	</div>
{% endblock body %}

accounts/templates/accounts/edit_profile.html
{% extends "base.html" %}
{% load static widget_tweaks inclusion_tags form_tags %}

{% block title %}
	Edit profile
{% endblock title %}

{% block search_form %}{% endblock search_form %}

{% block breadcrumb %}
	<li>
		<a href="{% url 'blog:author_profile' user.pk %}">
			<span class="icon is-small">
				<i class="fas fa-user" aria-hidden="true"></i>
			</span>
			User
		</a>
	</li>
	<li class="is-active">
		<span class="icon is-small">
			<i class="fas fa-user-edit" aria-hidden="true"></i>
		</span>
		Edit profile
	</li>
{% endblock breadcrumb %}

{% block content %}
	<div class="columns is-centered">
		<div class="column is-12-mobile is-6">
			<form method="post" novalidate enctype="multipart/form-data">
				{% csrf_token %}
				<div class="field columns">
					<div class="column is-5">
						<figure class="image thumbnail profile-picture is-1by1" id="picPreview" style="background-image: url({{ user.profile.profile_picture.url }}); box-shadow: 0px 0px 3px 1px hsl(0, 0%, 65%);"></figure>
					</div>
					<div class="column">
						<label class="label">{{ form.profile_picture.label_tag }}</label>
						{% render_field form.profile_picture id="imgInput" %}
						<p class="help">{{ form.profile_picture.help_text }}</p>
						{% field_errors form.profile_picture %}
					</div>
				</div>
				<div class="field mb-4">
					<label class="label">{{ form.about.label_tag }}</label>
					{% render_field form.about class=form.about|input_class %}
					<p class="help">{{ form.about.help_text }}</p>
					{% field_errors form.about %}
				</div>
				{% render_field_with_icon form.phone_number 'fas fa-phone' placeholder='0 426 684 3456' %}
				{% render_field_with_icon form.facebook_page 'fab fa-facebook-square' placeholder='https://www.facebook.com' %}
				{% render_field_with_icon form.twitter_profile 'fab fa-twitter-square' placeholder='https://www.twitter.com' %}
				{% render_field_with_icon form.instagram_profile 'fab fa-instagram-square' placeholder='https://www.instagram.com' %}
				<div class="buttons mb-2 is-centered">
					<button type="submit" class="button is-success is-block">Save changes</button>
					<a href="{% url 'blog:author_profile' user.pk %}" class="button is-block is-danger">Cancel</a>
				</div>
			</form>
			<small class="is-block has-text-centered">
				<a href="{% url 'accounts:settings' %}" class="has-text-grey">Account settings</a>
			</small>
		</div>
	</div>
{% endblock content %}

{% block javascript %}
	<script src="{% static "js/jquery-3.5.1.min.js" %}"></script>
	<script>
		function readURL(input) {
		    if (input.files && input.files[0]) {
		        var reader = new FileReader();
		        reader.onload = function (e) {
		            $('#picPreview').css('background-image', 'url(' + e.target.result + ')');
		            console.log(e.target.result)
		        }
		        reader.readAsDataURL(input.files[0]);
		    }
		}

		$("#imgInput").change(function(){
		   readURL(this);
		});
	</script>
{% endblock javascript %}

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}
{% load widget_tweaks form_tags inclusion_tags %}

{% block title %}
	Log in
{% endblock title %}

{% block left %}
	
{% endblock left %}

{% block content_right %}
	<form method="post" novalidate>
		{% csrf_token %}
		<input type="hidden" name='next' value="{{ next }}">
		{% include "includes/form_errors.html" %}
		{% render_field_with_icon form.username 'fas fa-user' label=False margin_bottom="" %}
		{% render_field_with_icon form.password 'fas fa-lock' label=False margin_bottom="" %}
		<hr>
		<button type="submit" class="button is-fullwidth is-info is-full mt-4">LOG IN</button>
	</form>
	<small class="column is-fullwidth has-text-centered has-text-grey mt-2 py-0">
		New to MyBlog?
		<a href="{% url 'accounts:signup' %}">Sign up</a>.
	</small>
	<small class="column is-fullwidth has-text-centered py-0">
		<a href="{% url 'accounts:password_reset' %}" class="has-text-grey">
			I forgot my password
		</a>
	</small>
{% endblock content_right %}

accounts/templates/accounts/settings.html
{% extends "base.html" %}
{% load form_tags %}

{% block title %}
	User settings
{% endblock title %}

{% block search_form %}{% endblock search_form %}

{% block breadcrumb %}
	<li>
		<a href="{% url 'blog:author_profile' user.pk %}">
			<span class="icon is-small">
				<i class="fas fa-user" aria-hidden="true"></i>
			</span>
			User
		</a>
	</li>
	<li class="is-active">
		<span class="icon is-small">
			<i class="fas fa-user-cog" aria-hidden="true"></i>
		</span>
		Settings
	</li>
{% endblock breadcrumb %}

{% block content %}
	<div class="columns">
		<div class="column is-full-mobile is-one-third-desktop">
			<form method="post" novalidate>
				{% csrf_token %}
				{% if form.non_field_errors %}
					<div class="notification is-danger">
						{% for error in form.non_field_errors %}
							<p>{{ error}}</li>
						{% endfor %}
					</div>
				{% endif %}
				{% render_field_with_icon form.first_name "fas fa-signature" %}
				{% render_field_with_icon form.last_name "fas fa-star-of-life" %}
				{% render_field_with_icon form.email "fas fa-envelope" %}
				<div class="buttons">
					<button type="submit" class="button is-success is-block">Save changes</button>
					<a href="{% url 'accounts:password_change' %}" class="button is-warning">Change password</a>
				</div>
			</form>
		</div>
	</div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "accounts/base.html" %}
{% load widget_tweaks form_tags %}

{% block title %}
	Sign up
{% endblock title %}

{% block left %}
	
{% endblock left %}

{% block content_right %}
	<form method="post" novalidate>
		{% csrf_token %}
		{% include "includes/form_errors.html" %}
		<div class="field -is-horizontal">
			<div class="field-body">
				{% render_field_with_icon form.first_name 'fas fa-signature' label=False margin_bottom="" %}
				<div class="field">
					{% render_field form.last_name class=form.last_name|input_class placeholder="Last name" %}
					{% field_errors form.last_name %}
				</div>
			</div>
		</div>
		{% render_field_with_icon form.username 'fas fa-user' label=False margin_bottom="mb-3" %}
		{% render_field_with_icon form.email 'fas fa-envelope' label=False margin_bottom="mb-3" %}
		<div class="field -is-horizontal">
			<div class="field-body">
				{% render_field_with_icon form.password1 'fas fa-lock' label=False margin_bottom="" help_text=False %}
				<div class="field">
					{% render_field form.password2 class=form.password2|input_class placeholder="Password confirmation" %}
					{% field_errors form.password2 %}
				</div>
			</div>
		</div>	
		<hr>
		<button type="submit" class="button is-fullwidth is-info is-full mt-4">SIGN UP</button>
	</form>
	<small class="column is-fullwidth has-text-centered has-text-grey py-3">
		Already have an account?
		<a href="{% url 'accounts:login' %}">Log in</a>.
	</small>
{% endblock content_right %}