blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
	path('explore/', views.ExploreView.as_view(), name='explore'),
	path('results/', views.search_results, name='search_results'),
	path('category/<int:pk>/', views.CategoryPostsView.as_view(), name='category'),
	path('article/new/', views.BlogPostCreateView.as_view(), name='new_article'),
	path('article/<slug:slug>/', views.BlogPostDetailView.as_view(), name='article'),
	path('article/<slug:slug>/comment/<int:pk>/edit/', views.BlogCommentUpdateView.as_view(), name='edit_comment'),
	path('author/<int:pk>/', views.UserDetailView.as_view(), name='author_profile'),
	path('author/<int:pk>/follow/', views.follow_author, name='follow_author'),
	path('author/<int:pk>/unfollow/', views.unfollow_author, name='unfollow_author')
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from accounts import urls as accounts_urls
from blog import urls as blog_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(blog_urls)),
    path('auth/', include(accounts_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.signals import post_delete, pre_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.utils.text import slugify, Truncator
from django.utils.html import mark_safe
from markdown import markdown

from accounts.models import Profile

DEFAULT_CATEGORY_ID = 1 # The id of the category all BlogPost objects will fall in by default.

def upload_location(instance, filename):
	return f'img/blog_thumbnails/author{instance.author.pk}/{instance.title}-thumbnail'

class BlogPost(models.Model):
	title = models.CharField(max_length=75, null=False, blank=False, unique=True)
	introduction = models.TextField(max_length=400, null=False, blank=False)
	body = models.TextField(max_length=25000, null=False, blank=False)
	thumbnail = models.ImageField(upload_to=upload_location, default='img/blog_thumbnails/default.jpg')
	author = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE, null=False)
	date_published  = models.DateTimeField(auto_now_add=True, verbose_name='date published') 
	date_updated  = models.DateTimeField(auto_now=True, verbose_name='date updated')
	categories = models.ManyToManyField('BlogCategory', default=DEFAULT_CATEGORY_ID, related_name='articles')
	slug = models.SlugField(blank=True, unique=True)

	def __str__(self):
		return self.title

	def get_body_as_markdown(self):
		return mark_safe(markdown(self.body, safe_mode='escape'))

	def get_truncated_introduction(self):
		return Truncator(self.introduction).chars(250)

	def get_ordered_comments(self):
		return self.comments.order_by('-created_at')

@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, *args, **kwargs):
	instance.image.delete(False)

def pre_save_blogpost_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(f'{instance.author.username}-{instance.title}')

pre_save.connect(pre_save_blogpost_receiver, sender=BlogPost)

class BlogComment(models.Model):
	message = models.CharField(max_length=600, blank=False)
	article = models.ForeignKey(BlogPost, related_name='comments', on_delete=models.CASCADE)
	created_by = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)
	edited_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return f'"{Truncator(self.message).chars(10)}" at {self.article}'


class UserFollowing(models.Model):
	user = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE)
	user_following = models.ForeignKey(User, related_name='followers', on_delete=models.CASCADE)
	date_followed = models.DateField(auto_now_add=True)

	class Meta:
		unique_together = ['user', 'user_following']

	def __str__(self):
		return f'{self.user} follows {self.user_following}'

class BlogCategory(models.Model):
	name = models.CharField(max_length=50, unique=True)
	color_choices = [
		('ISL', 'is-light'),
		('ISP', 'is-primary'),
		('ISL', 'is-link'),
		('ISI', 'is-info'),
		('ISS', 'is-success'),
		('ISW', 'is-warning'),
		('ISD', 'is-danger')
	]
	tag_color = models.CharField(max_length=10, choices=color_choices, default='is-light')

	def __str__(self):
		return self.name

blog/forms.py
from django import forms
from .models import BlogPost, BlogCategory, BlogComment

class SearchForm(forms.Form):
	query = forms.CharField(
		max_length=75,
		required=True,
		widget=forms.TextInput(attrs={'placeholder': 'Search content...'})
	)

class NewArticleForm(forms.ModelForm):
	body = forms.CharField(
		widget=forms.Textarea(
			attrs={'rows': 15, 'placeholder': 'My first article!'}
		),
		help_text='Max characters amount is 25000.'
	)

	introduction = forms.CharField(
		widget=forms.Textarea(
			attrs={'rows': 3, 'placeholder': 'Welcome to my article.'}
		),
		help_text='Introduction does not allow Markdown. More than one paragraph is not recommended. Max characters amount is 400.'
	)

	categories = forms.ModelMultipleChoiceField(
		queryset=BlogCategory.objects.all(),
		widget=forms.CheckboxSelectMultiple()
	)

	class Meta:
		model = BlogPost
		fields = ['title', 'thumbnail', 'introduction', 'body', 'categories', ]
		help_texts = {'thumbnail': 'Images with a 16x9 aspect ratio are recomemnded.'}

class NewCommentForm(forms.ModelForm):
	message = forms.CharField(
		widget=forms.Textarea(attrs={'rows': 3}),
		help_text='Max characters amount is 600. Comments do not allow Markdown.'
	)

	class Meta:
		model = BlogComment
		fields = ['message', ]

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView, FormView, DetailView, CreateView, UpdateView
from django.views.generic.base import ContextMixin
from django.views.generic.edit import FormMixin
from django.utils.decorators import method_decorator
from itertools import chain
from .forms import SearchForm, NewArticleForm, NewCommentForm
from .models import BlogPost, UserFollowing, BlogComment, BlogCategory

def order_by_attribute(listset, attr):
	l = list(listset)
	for i in range(len(l)):
		for j in range(i+1, len(l)):
			if getattr(l[i], attr).count() < getattr(l[j], attr).count():
				l[i], l[j] = l[j], l[i]

	return l

class SearchFormMixin(ContextMixin):
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['search_form'] = SearchForm()
		return context

@method_decorator(login_required, name='dispatch')
class BlogPostCreateView(CreateView, SearchFormMixin):
    model = BlogPost
    form_class = NewArticleForm
    template_name = "blog/new_blog_post.html"

    def form_valid(self, form):
    	article = form.save(commit=False)
    	article.author = self.request.user
    	article.save()
    	form.save_m2m()
    	return redirect('blog:article', slug=article.slug)

@method_decorator(login_required, name='dispatch')
class BlogCommentUpdateView(UpdateView):
    model = BlogComment
    form_class = NewCommentForm
    template_name = "blog/edit_comment.html"

    def get(self, request, *args, **kwargs):
    	comment = self.get_object()
    	form = NewCommentForm()
    	form.initial['message'] = comment.message
    	if request.user == comment.created_by:
    		return render(request, 'blog/edit_comment.html', {'comment': comment, 'form': form})
    	
    	return redirect('blog:article', slug=self.kwargs['slug'])

    def get_success_url(self):
    	return reverse_lazy('blog:article', kwargs={'slug': self.kwargs['slug']})

class HomeView(TemplateView, SearchFormMixin):
	template_name = 'blog/home.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		user = self.request.user
		latest = list()
		following = list()
		if user.is_authenticated:
			if user.following.exists():
				following = [f.user_following for f in (user.following.all())] 
				latest = BlogPost.objects.filter(author__in=following).order_by('-date_published')[:12]
				following.append(user)

		fill = BlogPost.objects.exclude(author__in=following).order_by('-date_published')
		latest = list(chain(latest, fill[:12]))
		context['latest_articles'] = latest[:12]
		context['popular_articles'] = context['latest_articles']
		return context

class ExploreView(TemplateView, SearchFormMixin):
	template_name = "blog/explore.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		category_sets = list()
		for c in (BlogCategory.objects.all()):
			articles = BlogPost.objects.filter(categories__in=[c])[:8]
			category_set = {'category': c, 'articles': articles}
			category_sets.append(category_set)

		context['category_sets'] = category_sets
		context['popular_authors'] = order_by_attribute(User.objects.all()[:20], 'followers')
		return context

class CategoryPostsView(DetailView, SearchFormMixin):
	template_name = 'blog/category_articles.html'
	model = BlogCategory
	context_object_name = 'category'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		category = self.get_object()
		context['articles'] = BlogPost.objects.filter(categories__in=[category])
		return context

class BlogPostDetailView(CreateView, SearchFormMixin):
	model = BlogComment
	form_class = NewCommentForm
	template_name = "blog/blog_post.html"

	def form_valid(self, form):
		article = get_object_or_404(BlogPost, slug=self.kwargs['slug'])
		self.object = form.save(commit=False)
		self.object.created_by = self.request.user
		self.object.article = article
		self.object.save()
		return redirect('blog:article', slug=article.slug)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['article'] = get_object_or_404(BlogPost, slug=self.kwargs['slug'])
		return context

class UserDetailView(DetailView, SearchFormMixin):
    model = User
    context_object_name = 'author'
    template_name = "blog/user_profile.html"

@login_required
def follow_author(request, pk):
	author = get_object_or_404(User, pk=pk)
	new_follower = UserFollowing.objects.filter(user=request.user, user_following=author)
	if not new_follower.exists():
		new_follower = UserFollowing.objects.create(user=request.user, user_following=author)

	return redirect('blog:author_profile', pk=pk)

@login_required
def unfollow_author(request, pk):
	author = get_object_or_404(User, pk=pk)
	follower = UserFollowing.objects.filter(user=request.user, user_following=author)
	if follower.exists():
		follower.delete()

	return redirect('blog:author_profile', pk=pk)
	
def search_results(request):
	if request.method == 'POST':
		form = SearchForm(request.POST)
		if form.is_valid():
			search_query = form.cleaned_data.get('query')
			articles = []
			for a in (BlogPost.objects.all()):
				if a.title.lower().find(search_query.lower()) != -1:
					articles.append(a)

			return render(request, 'blog/search_results.html', {'articles': articles, 'search_form': form, 'query': search_query})
	
	else:
		form = SearchForm()

	return redirect('blog:home')

blog/templates/blog/blog_post.html
{% extends "base.html" %}
{% load static inclusion_tags widget_tweaks form_tags %}

{% block stylesheets %}
	<link rel="stylesheet" href="{% static "css/blog_post.css" %}">
{% endblock stylesheets %}

{% block title %}
	{{ article.title }}
{% endblock title %}

{% block breadcrumb %}
	<li>
		<a href="{% url 'blog:home' %}">
			<span class="icon is-small">
				<i class="fas fa-home" aria-hidden="true"></i>
			</span>
			Home
		</a>
	</li>
	<li>
		<a href="#">
			<span class="icon is-small">
				<i class="fas fa-user-edit" aria-hidden="true"></i>
			</span>
			Authors
		</a>
	</li>
	<li>
		<a href="{% url 'blog:author_profile' article.author.pk %}">
			<span class="icon is-small">
				<i class="fas fa-user" aria-hidden="true"></i>
			</span>
			{{ article.author.username }}
		</a>
	</li>
	<li class="is-active">
		<span class="icon is-small">
			<i class="fas fa-book-reader" aria-hidden="true"></i>
		</span>
		{{ article.title }}
	</li>
{% endblock breadcrumb %}

{% block content %}
	<div class="columns">
		<div class="column content is-full-mobile">
			<div>
				<div class="tags mb-1">
					{% for category in article.categories.all %}
						{% render_tag category %}
					{% endfor %}
				</div>
				<hr class="mt-1 mb-3">
				<p class="title is-5 is-size-6-mobile has-text-centered mb-2">
					{{ article.title }}
				</p>
				<p class="is-5 has-text-centered" title="{{ article.date_published}}">
					<span class="icon">
						<i class="fas fa-calendar-alt"></i>
					</span>
					{{ article.date_published|date:"d.m.Y" }} 
					<span class="is-hidden-desktop"> by
						<a href="{% url 'blog:author_profile' article.author.pk %}" class="has-text-grey">{{ article.author.username }}</a>
					</span>
				</p>
				<figure class="image is-fullwidth is-16by9 mx-0 my-0">
					<img src="{{ article.thumbnail.url }}" alt="article thumbnail">
				</figure>
				<div class="body mt-4">
					<p>{{ article.introduction }}</p>
					<p>{{ article.get_body_as_markdown }}</p>
				</div>
			</div>
			<hr>
			<div class="mb-4">
				{% if user.is_authenticated %}
					<form method="post" novalidate>
						{% csrf_token %}
						<p class="label title is-5">Leave a comment!</p>
						<div class="field">
							<div class="control">
								{% render_field form.message class=form.message|input_class placeholder="Nice post!" %}
							</div>
							<p class="help">{{ form.message.help_text }}</p>
							{% field_errors form.message %}
						</div>
						<button type="submit" class="button is-dark is-fullwidth">Add comment</button>
					</form>
				{% endif %}
			</div>
			<p class="has-text-grey-dark is-size-5 mb-5">{{ article.comments.count }} comments</p>
			{% for comment in article.get_ordered_comments %}
				<div class="columns box mb-5 mx-1 py-1 pl-2 pr-1 pb-3 is-mobile">
					<div class="column is-1 is-hidden-mobile pl-1 pr-0">
						<figure class="image thumbnail is-square mx-0 profile-picture" style="background-image: url({{ comment.created_by.profile.profile_picture.url }});"></figure>
					</div>
					<div class="column pb-0">			
						<div class="columns mb-0 pb-1 is-mobile">
							<p class="column mb-0 pb-0"><strong><a href="{% url 'blog:author_profile' comment.created_by.pk %}" class="has-text-grey-dark">{{ comment.created_by.username }}</strong></a> says:</p>
							<small class="column  has-text-grey has-text-right pr-3 pb-0">{{ comment.created_at }}</small>	
						</div> 
						<p class="mb-0">{{ comment.message}}</p>
						{% if user == comment.created_by %}
							<a href="{% url 'blog:edit_comment' article.slug comment.pk %}" class="is-block has-text-right has-text-grey">edit</a>
						{% endif %}
					</div>
				</div>
			{% endfor %}
		</div>
		<hr class="is-hidden-desktop">
		<div class="column is-one-fifth mt-2 mr-4 pl-0">
			<p class="level is-size-5">About the author:</p>
			<div class="columns">
				<div class="column is-4 is-3-mobile px-0 py-0">
					<figure class="image thumbnail is-1by1 has-background-link-light profile-picture" style="background-image: url({{ article.author.profile.profile_picture.url }});"></figure>
				</div>
				<p class="title-6 column pr-0 pb-0 is-vcentered">
					{{ article.author.profile.get_full_name }}
					<br>
					<a href="{% url 'blog:author_profile' article.author.pk %}" class="has-text-grey">@{{ article.author.username }}</a>
				</p>
			</div>
			<div class="info mt-2">
				<hr class="my-2">
				<small>{{ article.author.profile.about }}</small>
				<hr class="my-2">
			</div>
			<div class="icons">
				{% social_icons article.author %}
			</div>
		</div>
	</div>
{% endblock content %}

blog/templates/blog/category_articles.html
{% extends "base.html" %}

{% block title %}
	{{ category.name }} Posts
{% endblock title %}

{% block breadcrumb %}
	<li>
		<a href="{% url 'blog:explore' %}">
			<span class="icon is-small">
				<i class="fas fa-search" aria-hidden="true"></i>
			</span>
			Explore
		</a>
	</li>
	<li class="is-active">
		<span class="icon is-small">
			<i class="fas fa-list" aria-hidden="true"></i>
		</span>
		{{ category.name }}
	</li>
{% endblock breadcrumb %}

{% block content %}
	<p class="title is-5 mb-5">Category: {{ category.name }}</p>
	{% if articles|length > 0 %}
		<div class="column pt-5 is-10">
			<div class="columns is-mobile is-multiline is-centered" >
				{% for article in articles %}
					{% include "blog/includes/article_row.html" with author_name=True %}
				{% endfor %}
			</div>
		</div>
	{% else %}
		<p class="has-text-centered has-text-grey">No articles to show for this category.</p>
	{% endif %}
{% endblock content %}

blog/templates/blog/edit_comment.html
{% extends "base.html" %}
{% load widget_tweaks form_tags %}

{% block title %}
	Edit comment
{% endblock title %}

{% block search_form %}{% endblock search_form %}

{% block breadcrumb %}
	<li>
		<a href="{% url 'blog:home' %}">
			<span class="icon is-small">
				<i class="fas fa-home" aria-hidden="true"></i>
			</span>
			Home
		</a>
	</li>
	<li>
		<a href="#">
			<span class="icon is-small">
				<i class="fas fa-user-edit" aria-hidden="true"></i>
			</span>
			Authors
		</a>
	</li>
	<li>
		<a href="{% url 'blog:author_profile' comment.article.author.pk %}">
			<span class="icon is-small">
				<i class="fas fa-user" aria-hidden="true"></i>
			</span>
			{{ comment.article.author.username }}
		</a>
	</li>
	<li>
		<a href="{% url 'blog:article' comment.article.slug %}">
			<span class="icon is-small">
				<i class="fas fa-book-reader" aria-hidden="true"></i>
			</span>
			{{ comment.article.title }}
		</a>
	</li>
	<li class="is-active">
		<span class="icon is-small">
			<i class="fas fa-edit"></i>
		</span>
		Edit comment
	</li>
{% endblock breadcrumb %}

{% block content %}
	<form method="post" novalidate>
		{% csrf_token %}

		<div class="field">
			<label class="label">{{ form.message.label_tag }}</label>
			<div class="control">
				{% render_field form.message class=form.message|input_class %}
			</div>
			{% field_errors form.message %}
		</div>
		<div class="buttons">
			<button type="submit" class="button is-success">Apply changes</button>
			<a href="{% url 'blog:article' comment.article.slug %}" class="button is-danger">Cancel</a>
		</div>
	</form>
{% endblock content %}

blog/templates/blog/explore.html
{% extends "base.html" %}

{% block title %}
	Explore
{% endblock title %}

{% block breadcrumb %}
	<li>
		<span class="icon is-small">
			<i class="fas fa-search" aria-hidden="true"></i>
		</span>
		Explore
	</li>
{% endblock breadcrumb %}

{% block content %}
	{% for set in category_sets %}
		{% if set.articles|length > 0 %}
			<p class="subtitle is-4 mb-5 mt-2">
				<a href="{% url 'blog:category' set.category.pk %}" class="has-text-grey-darker">{{ set.category.name }}:</a>
			</p>
			<div class="columns is-multiline">
				{% for article in set.articles %}
					{% include "blog/includes/article_card.html" with article=article size="is-one-quarter" %}
				{% endfor %}
			</div>
		{% endif %}
	{% endfor %}
	<p class="mb-2 mt-2 subtitle is-4">Popular authors:</p>
	<div class="level">
		<ul>
			{% for author in popular_authors %}
				<li><a href="{% url 'blog:author_profile' author.pk %}">{{ author.username }} - {{ author.followers.count }} followers</a></li>
			{% endfor %}
		</ul>
	</div>
{% endblock content %}

blog/templates/blog/home.html
{% extends "base.html" %}

{% block title %}
	MyBlog - Home
{% endblock title %}

{% block content %}
	<p class="mb-5 subtitle is-4">Latest posts:</p>
	<div class="columns">
		{% include "blog/includes/article_card.html" with article=latest_articles.0 size="is-half" %}
		<div class="columns column is-multiline py-5">
			{% for article in latest_articles|slice:"1:4" %}
				{% include "blog/includes/article_row_small.html" with article=article %}
			{% endfor %}
		</div>
	</div>
	<div class="columns is-multiline mt-3">
		{% for article in latest_articles|slice:"4:" %}
			{% include "blog/includes/article_card.html" with article=article size="is-one-quarter" %}
		{% endfor %}
	</div>
	<p class="mb-5 mt-2 subtitle is-4">Popular articles:</p>
	<div class="columns is-multiline">
		{% for article in popular_articles %}
			{% include "blog/includes/article_card.html" with article=article size="is-one-quarter" %}
		{% endfor %}
	</div>
{% endblock content %}

blog/templates/blog/new_blog_post.html
{% extends "base.html" %}
{% load static widget_tweaks form_tags inclusion_tags %}

{% block title %}
	Create an article
{% endblock title %}

{% block stylesheets %}
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock stylesheets %}

{% block breadcrumb %}
	<li>
		<a href="{% url 'blog:home' %}">
			<span class="icon is-small">
				<i class="fas fa-home" aria-hidden="true"></i>
			</span>
			Home
		</a>
	</li>
	<li class="is-active">
		<span class="icon is-small">
			<i class="fas fa-pen-nib" aria-hidden="true"></i>
		</span>
		Create an article
	</li>
{% endblock breadcrumb %}

{% block content %}
	<div class="columns is-centered">
		<div class="column is-three-quarters">
			<form method="post" novalidate enctype="multipart/form-data">
				{% csrf_token %}
				{% render_field_with_icon form.title 'fas fa-heading' placeholder='My first article' %}
				<div class="field mb-4">
					<label class="label">{{ form.thumbnail.label_tag }}</label>
					{% render_field form.thumbnail %}
					<p class="help">{{ form.thumbnail.help_text }}</p>
					{% field_errors form.thumbnail %}
				</div>
				<div class="field mb-4">
					<label class="label">{{ form.introduction.label_tag }}</label>
					{% render_field form.introduction class=form.introduction|input_class placeholder=form.introduction.placeholder %}
					<p class="help mt-0 pt-0">{{ form.introduction.help_text }}</p>
					{% field_errors form.introduction %}
				</div>
				<div class="field mb-4">
					<label class="label">{{ form.body.label_tag }}</label>
					{% render_field form.body class=form.body|input_class placeholder=form.body.placeholder id="body" %}
					<p class="help mt-0 pt-0">{{ form.body.help_text }}</p>
					{% field_errors form.body %}
				</div>
				<div class="field mb-4 categories">
					<label class="label">{{ form.categories.label_tag }}</label>
					<div class="columns is-multiline py-2 pl-3" id="id_categories">
						{% for category in form.categories %}
							<div class="column is-one-fifth py-1">
								<label for="id_categories">
									{{ category.tag }} {{ category.choice_label }}
								</label>
							</div>
						{% endfor %}
					</div>
					{% field_errors form.categories %}
				</div>
				<div class="columns mt-5">
					<div class="column">
						<button type="submit" class="button is-primary is-fullwidth">Create</button>
					</div>
					<div class="column">
						<a href="{% url 'blog:home' %}" class="button is-link is-fullwidth">Cancel</a>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock content %}

{% block javascript %}
	<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
	<script src="{% static "js/jquery-3.5.1.min.js" %}"></script> <script>
		var simplemde = new SimpleMDE({element: $("#body")[0]});
	</script>
{% endblock javascript %}

blog/templates/blog/search_results.html
{% extends "base.html" %}

{% block title %}
	Results - {{ query }}
{% endblock title %}

{% block breadcrumb %}
	<li>
		<a href="{% url 'blog:home' %}">
			<span class="icon is-small">
				<i class="fas fa-home" aria-hidden="true"></i>
			</span>
			Home
		</a>
	</li>
	<li class="is-active">
		<span class="icon is-small">
			<i class="fas fa-search" aria-hidden="true"></i>
		</span>
		Search results
	</li>
{% endblock breadcrumb %}

{% block content %}
	<p class="title is-6 mb-5">{{ articles|length }} results for: {{ query }}</p>
	<div class="columns">
		<div class="column is-10">
			{% for article in articles %}
				{% include "blog/includes/article_row.html" with article=article author_name=True %}
			{% endfor %}
		</div>
	</div>
{% endblock content %}

blog/templates/blog/user_profile.html
{% extends "base.html" %}
{% load static inclusion_tags %}

{% block stylesheets %}
	<link rel="stylesheet" href="{% static "css/user_profile.css" %}">
{% endblock stylesheets %}

{% block title %}
	{{ author.username }}'s profile
{% endblock title %}

{% block breadcrumb %}
	{% if author == user %}
		<li class="is-active">
			<span class="icon is-small">
				<i class="fas fa-user" aria-hidden="true"></i>
			</span>
			User
		</li>
	{% else %}
		<li>
			<a href="{% url 'blog:home' %}">
				<span class="icon is-small">
					<i class="fas fa-home" aria-hidden="true"></i>
				</span>
				Home
			</a>
		</li>
		<li>
			<a href="#">
				<span class="icon is-small">
					<i class="fas fa-user-edit" aria-hidden="true"></i>
				</span>
				Authors
			</a>
		</li>
		<li class="is-active">
			<span class="icon is-small">
				<i class="fas fa-user" aria-hidden="true"></i>
			</span>
			{{ author.username }}'s profile
		</li>
	{% endif %}
{% endblock breadcrumb %}

{% block content %}
	<div class="columns">
		<div class="column is-one-fifth is-full-mobile">
			<div class="box px-5 mb-1">
				<figure class="image thumbnail is-1by1 profile-picture has-background-link-light mx-0" style="background-image: url({{ author.profile.profile_picture.url }});">
				</figure>
				<div class="info mt-3">
					<p class="title-6">{{ author.profile.get_full_name }}</p>
					<small class="has-text-grey">@{{ author.username }}</small>
					<hr class="my-2">
					<small>{{ author.profile.about }}</small>
					<hr class="my-2">
				</div>
				<div class="icons">
					{% social_icons author %}
				</div>
			</div>
			{% if user.is_authenticated %}
				{% if author == user %}
					<p class="tags has-addons is-centered mt-2 mb-0">
						{% follow_tag_button author disabled=True %}
						<span class="tag is-light has-text-grey">
							{{ author.followers.count }}
						</span>
					</p>
				{% else %}
					<div class="columns is-centered pt-2">
						<div class="column">
							<p class="tags has-addons is-centered">
								{% follow_tag_button author user %}
								<span class="tag is-light">
									{{ author.followers.count }}
								</span>
							</p>
						</div>
					</div>
				{% endif %}
			{% else %}
				<p class="tags has-addons is-centered mt-2 mb-0">
					{% follow_tag_button author disabled=True %}
					<span class="tag is-light has-text-grey">
						{{ author.followers.count }}
					</span>
				</p>
			{% endif %}
		</div>
		<div class="is-hidden-desktop">
			<hr>
			<p class="title is-4 ml-4">Articles:</p>
		</div>
		<div class="column pt-5 ml-3">
			<div class="columns is-mobile is-multiline is-centered" >
				{% for article in author.profile.get_ordered_posts %}
					{% include "blog/includes/article_row.html" %}
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}