accounts/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),

	path('signup/', views.SignUpView.as_view(), name='signup'),
	path('settings/', views.UserUpdateView.as_view(), name='settings'),
	path('edit/', views.ProfileUpdateView.as_view(), name='edit_profile'),

	path('password/reset/', auth_views.PasswordResetView.as_view(
		template_name='accounts/password_reset/password_reset.html',
		email_template_name='accounts/password_reset/password_reset_email.html',
		subject_template_name='accounts/password_reset/password_reset_subject.html',
		success_url=reverse_lazy('accounts:password_reset_done')
		),
		name='password_reset'
	),
	path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset/password_reset_done.html'), name='password_reset_done'),
	re_path(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
		auth_views.PasswordResetConfirmView.as_view(
			template_name='accounts/password_reset/password_reset_confirm.html',
			success_url=reverse_lazy('accounts:passsword_reset_complete')
		),
		name='password_reset_confirm'
	),
	path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/password_reset_complete.html'), name='passsword_reset_complete'),

	path('password/change/', 
		auth_views.PasswordChangeView.as_view(
			template_name='accounts/password_change/password_change.html',
			success_url=reverse_lazy('accounts:password_change_done')
		),
		name='password_change'
	),
	path('password/change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
	path('explore/', views.ExploreView.as_view(), name='explore'),
	path('results/', views.search_results, name='search_results'),
	path('category/<int:pk>/', views.CategoryPostsView.as_view(), name='category'),
	path('article/new/', views.BlogPostCreateView.as_view(), name='new_article'),
	path('article/<slug:slug>/', views.BlogPostDetailView.as_view(), name='article'),
	path('article/<slug:slug>/comment/<int:pk>/edit/', views.BlogCommentUpdateView.as_view(), name='edit_comment'),
	path('author/<int:pk>/', views.UserDetailView.as_view(), name='author_profile'),
	path('author/<int:pk>/follow/', views.follow_author, name='follow_author'),
	path('author/<int:pk>/unfollow/', views.unfollow_author, name='unfollow_author')
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from accounts import urls as accounts_urls
from blog import urls as blog_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(blog_urls)),
    path('auth/', include(accounts_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}{% endblock title %}</title>
		<link rel="stylesheet" href="{% static "css/base.css" %}">
		<link rel="stylesheet" href="{% static "css/bulma.min.css" %}">
		<link rel="stylesheet" href="{% static "css/all.css" %}">
		{% block stylesheets %}{% endblock stylesheets %}
	</head>

	<body class="has-navbar-fixed-top">
		{% block body %}
			<nav class="navbar is-light is-fixed-top" role="navigation" aria-label="main navigation" style="box-shadow: 0px 0px 2px 0.5px hsl(0, 0%, 70%);">
				<div class="navbar-brand mx-3">
					<a href="{% url 'blog:home' %}">
						<img class="py-2 px-2" src="{% static "img/logopng.png" %}" alt="MyBlog logo" width="85" height="50">
					</a>
					<a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
					  <span aria-hidden="true"></span>
					  <span aria-hidden="true"></span>
					  <span aria-hidden="true"></span>
					</a>
				</div>
				<div class="navbar-menu">
					<div class="navbar-start">
						<a href="{% url 'blog:home' %}" class="navbar-item">Home</a>
						<a href="{% url 'blog:explore' %}" class="navbar-item">Explore</a>
						<a href="#" class="navbar-item">About</a>
					</div>
					<div class="navbar-end">
						<div class="navbar-item">
							{% block search_form %}
								<form method="post" action="{% url 'blog:search_results' %}" novalidate>
									{% csrf_token %}
									<div class="field has-addons">
										<div class="control">
											{% render_field search_form.query class="input" %}
										</div>
										<div class="control">
											<button type="submit" class="button is-info">
												<i class="fas fa-search"></i>
											</button>
										</div>
										</p>
									</div>
								</form>
							{% endblock search_form %}
							{% if user.is_authenticated %}
								<a href="{% url 'blog:new_article' %}" title="create article" class="button is-primary ml-2">
									<span class="icon is-small">
										<i class="fas fa-plus"></i>
									</span>
								</a>
								<div class="navbar-item has-dropdown dropdown ml-2">
									<a class="navbar-link dropdown-trigger">{{ user.username }}</a>
									<div class="navbar-dropdown dropdown-menu">
										<a href="{% url 'blog:author_profile' user.pk %}" class="navbar-item">Profile</a>
										<a href="{% url 'accounts:edit_profile' %}" class="navbar-item">About you</a>
										<a href="{% url 'accounts:settings' %}" class="navbar-item">Settings</a>
										<hr class="navbar-divider">
										<a href="{% url 'accounts:logout' %}" class="navbar-item">Log out</a>
									</div>
								</div>
							{% else %}
								<div class="buttons ml-5">
									<a href="{% url 'accounts:login' %}" class="button is-info">Log in</a>
									<a href="{% url 'accounts:signup' %}" class="button is-primary">Sign up</a>
								</div>
							{% endif %}
						</div>
					</div>
				</div>
			</nav>
			<div class="breadcrumb is-left pt-3 mb-2" aria-label="breadcrumbs">
				<ul class="py-1 pl-2" style="background: hsl(0, 0%, 97%);">
					{% block breadcrumb %}
					<li class="is-active">
						<span class="icon is-small">
							<i class="fas fa-home" aria-hidden="true"></i>
						</span>
						Home
					</li>
					{% endblock breadcrumb %}
				</ul>
			</div>

			<section class="section pt-4 has-text-grey">
				
				<div class="container">
					{% block content %}
						
					{% endblock content %}
				</div>
			</section>
		{% endblock body %}

		<script src="{% static "js/bulma/bulma.js" %}"></script>
		{% block javascript %}{% endblock javascript %}
	</body>
</html>