accounts/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),

	path('signup/', views.SignUpView.as_view(), name='signup'),
	path('settings/', views.UserUpdateView.as_view(), name='settings'),
	path('edit/', views.ProfileUpdateView.as_view(), name='edit_profile'),

	path('password/reset/', auth_views.PasswordResetView.as_view(
		template_name='accounts/password_reset/password_reset.html',
		email_template_name='accounts/password_reset/password_reset_email.html',
		subject_template_name='accounts/password_reset/password_reset_subject.html',
		success_url=reverse_lazy('accounts:password_reset_done')
		),
		name='password_reset'
	),
	path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset/password_reset_done.html'), name='password_reset_done'),
	re_path(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
		auth_views.PasswordResetConfirmView.as_view(
			template_name='accounts/password_reset/password_reset_confirm.html',
			success_url=reverse_lazy('accounts:passsword_reset_complete')
		),
		name='password_reset_confirm'
	),
	path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/password_reset_complete.html'), name='passsword_reset_complete'),

	path('password/change/', 
		auth_views.PasswordChangeView.as_view(
			template_name='accounts/password_change/password_change.html',
			success_url=reverse_lazy('accounts:password_change_done')
		),
		name='password_change'
	),
	path('password/change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
	path('explore/', views.ExploreView.as_view(), name='explore'),
	path('results/', views.search_results, name='search_results'),
	path('category/<int:pk>/', views.CategoryPostsView.as_view(), name='category'),
	path('article/new/', views.BlogPostCreateView.as_view(), name='new_article'),
	path('article/<slug:slug>/', views.BlogPostDetailView.as_view(), name='article'),
	path('article/<slug:slug>/comment/<int:pk>/edit/', views.BlogCommentUpdateView.as_view(), name='edit_comment'),
	path('author/<int:pk>/', views.UserDetailView.as_view(), name='author_profile'),
	path('author/<int:pk>/follow/', views.follow_author, name='follow_author'),
	path('author/<int:pk>/unfollow/', views.unfollow_author, name='unfollow_author')
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from accounts import urls as accounts_urls
from blog import urls as blog_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(blog_urls)),
    path('auth/', include(accounts_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field import modelfields
from . import validators

def upload_location(instance, filename):
	return f'img/profile_pictures/author{instance.user.pk}-picture'

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=False)
	about = models.CharField(max_length=250, null=True, blank=True)
	profile_picture = models.ImageField(upload_to=upload_location, default='img/profile_pictures/default.png')
	phone_number = modelfields.PhoneNumberField(null=True, blank=True)
	facebook_page = models.URLField(max_length=150, null=True, blank=True, validators=[validators.validate_facebook_url])
	twitter_profile = models.URLField(max_length=150, null=True, blank=True, validators=[validators.validate_twitter_url])
	instagram_profile = models.URLField(max_length=150, null=True, blank=True, validators=[validators.validate_instagram_url])

	def __str__(self):
		return f"{self.user.username}'s profile"

	def get_full_name(self):
		return f'{self.user.first_name} {self.user.last_name}'

	def get_ordered_posts(self):
		return self.user.posts.all().order_by('-date_published')

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class SignUpForm(UserCreationForm):
	email = forms.CharField(
		max_length=80,
		required=True,
		widget=forms.EmailInput()
	)

	first_name = forms.CharField(
		max_length=60,
		required=True,
		widget=forms.TextInput()
	)

	last_name = forms.CharField(
		max_length=60,
		required=True,
		widget=forms.TextInput()
	)

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

class UpdateUserForm(forms.ModelForm):
	email = forms.EmailField()

	first_name = forms.CharField(
		max_length=60,
		required=True,
		widget=forms.TextInput()
	)

	last_name = forms.CharField(
		max_length=60,
		required=True,
		widget=forms.TextInput()
	)

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email']

class UpdateProfileForm(forms.ModelForm):
	about = forms.CharField(
		widget=forms.Textarea(
			attrs={'rows': 4, 'placeholder': 'About me'}
		),
		required=False,
		help_text = 'Max characters amount is 250.'
	)

	class Meta:
		model = Profile
		fields = ['profile_picture', 'about', 'phone_number', 'instagram_profile', 'facebook_page', 'twitter_profile']
		help_texts = {'profile_picture': 'Square images are recomended.'}

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import SignUpForm, UpdateProfileForm, UpdateUserForm
from .models import Profile
from blog.views import SearchFormMixin

class SignUpView(CreateView, SearchFormMixin):
	model = User
	form_class = SignUpForm
	template_name = 'accounts/signup.html'

	def form_valid(self, form):
		user = form.save()
		profile = Profile.objects.create(user=user)
		profile.save()
		login(self.request, user)
		return redirect('blog:home')

@method_decorator(login_required, name='dispatch')
class UserUpdateView(UpdateView, SearchFormMixin):
    model = User
    form_class = UpdateUserForm
    template_name = "accounts/settings.html"
    success_url = reverse_lazy('accounts:settings')

    def get_object(self):
    	return self.request.user

    def form_valid(self, form):
    	super().form_valid(form)
    	return redirect('blog:author_profile', pk=self.object.pk)

@method_decorator(login_required, name='dispatch')
class ProfileUpdateView(UpdateView, SearchFormMixin):
    model = Profile
    form_class = UpdateProfileForm
    template_name = "accounts/edit_profile.html"
    success_url = reverse_lazy('accounts:edit_profile')

    def get_object(self):
    	return self.request.user.profile

    def form_valid(self, form):
    	super().form_valid(form)
    	return redirect('blog:author_profile', pk=self.object.user.pk)

@method_decorator(login_required, name='dispatch')
class PasswordChangeDone(TemplateView, SearchFormMixin):
    template_name = "accounts/password_change/password_change_done.html"

accounts/templates/accounts/password_reset/password_reset.html
{% extends "accounts/base.html" %}
{% load form_tags %}

{% block title %}
	Reset your password
{% endblock title %}

{% block right %}{% endblock right %}

{% block content_left %}
	<p class="title is-5 has-text-grey">Reset your password</p>
	<form method="POST" novalidate>
		{% csrf_token %}
		{% render_field_with_icon form.email 'fas fa-envelope' label=False margin_bottom="mb-4" %}
		<button type="submit" class="button is-info is-fullwidth">Send email</button>
	</form>
	<small class="has-text-grey is-block has-text-centered mt-2">
		Back to 
		<a href="{% url 'accounts:login' %}">login page</a>.
	</small>
{% endblock content_left %}

accounts/templates/accounts/password_reset/password_reset_complete.html
{% extends "accounts/base.html" %}
{% load form_tags %}

{% block title %}
	Password changed
{% endblock title %}

{% block right %}{% endblock right %}

{% block content_left %}
	<p class="title is-5 has-text-grey">Password changed</p>
	<p class="notification is-success mb-2">
		Your password has been changed successfully.
		<br>
		You many now proceed to log in.
	</p>
	<a href="{% url 'accounts:login' %}" class="is-block has-text-centered has-text-grey">Go to login page</a>
{% endblock content_left %}

accounts/templates/accounts/password_reset/password_reset_confirm.html
{% extends "accounts/base.html" %}
{% load form_tags %}

{% block title %}
	Reset your password
{% endblock title %}

{% block right %}{% endblock right %}

{% block content_left %}
	<p class="title is-5 has-text-grey">Reset your password</p>
	{% if validlink %}
		<form method="post" novalidate>
			{% csrf_token %}
			{% render_field_with_icon form.new_password1 'fas fa-lock' label=False help_text=False %}
			{% render_field_with_icon form.new_password2 'fas fa-star-of-life' label=False help_text=False %}
			<button type="submit" class="button is-fullwidth is-info is-full mt-4">Reset password</button>
		</form>
	{% else %}
		<p class="notification is-danger mb-2">
			Looks like you clicked on an invalid password reset link. Please try again.
		</p>
		<a href="{% url 'accounts:password_reset' %}" class="is-block has-text-centered has-text-grey">Request a new link</a>
	{% endif %}
{% endblock content_left %}

accounts/templates/accounts/password_reset/password_reset_done.html
{% extends "accounts/base.html" %}

{% block title %}
	Reset your password
{% endblock title %}

{% block right %}{% endblock right %}

{% block content_left %}
	<p class="title is-5 has-text-grey">Reset your password</p>
	<p class="mb-3">Check your email for  link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
	<small class="has-text-grey">
		Back to 
		<a href="{% url 'accounts:login' %}">login page</a>.
	</small>
{% endblock content_left %}

accounts/templates/accounts/password_reset/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Myblog username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Myblog team.

accounts/templates/accounts/password_reset/password_reset_subject.html
[Myblog] Please reset your password